### ISSUE TITLE
Dockerfile installation

### ISSUE THREAD

**Issue by Geronium** [commandprompt/pgmanage#318]
Hello, i tried to use the dockerfile, and this step doesn't work 

RUN python3 -c "$(curl -fsSL https://pgsql-io-download.s3.amazonaws.com/REPO/install.py)"

the link is broken, do you have an other link ? 

Thank you

**Comment by AbdelatifAitBara** [comment]
Hello @Geronium ,

Could you try this one : 

https://pgedge-download.s3.amazonaws.com/REPO/install.py

I hope it will work.

**Comment by Geronium** [comment]
Thank you, i juste tried with this link but the application is not the same, we don't have in the directory the io but this files 

/pgedge/ctl
/pgedge/nc
/pgedge/nodectl
/pgedge/pgedge

/pgedge/conf:
backup
cache
cli.pid
db_local.db
versions.sql
versions.sql.sha512

/pgedge/ctlibs:
README.md
config-ctlibs.py
install-ctlibs.py

/pgedge/data:
logs

/pgedge/hub:
doc
scripts

/pgedge/logs:
cli_log.out

And when i tried to use the nodectl i got this error 

⚠ 'nc', 'nodectl', & 'ctl' commands deprecated in favor of 'pgedge'
✘ Invalid component parameter (instantclient)


and the pgedge don't work like io, do you have a valid Dockerfile ?

**Comment by eug3nix** [comment]
Hi everyone. The mentioned Dockerfile was a part of the orinal project and it was no longer functional in PgManage project.
If you want to spin-up a local development copy please follow the instructions in Readme: https://github.com/commandprompt/pgmanage#run-your-local-development-copy-of-pgmanage-on-ubuntu

We are planning to start publishing intermediate builds with the latest updates in the Releases section of Github project soon.
For now, If you just want a user-friendly installation copy of the app, you can binaries here: https://www.commandprompt.com/products/pgmanage/

I have removed the Dockerfile to avoid further confusion.

Thanks,
Eugene

**Comment by Geronium** [comment]
Hello, thank you for your answer.

I'm trying to build a docker version, i read the readme but he didn't give the step to install instant client and ora2pg, we don't need this application to use pgmanage with oracle ? 

i tried to build a docker image in july with the previous version of pgmanage, and the step 

RUN python3 -c "$(curl -fsSL https://pgsql-io-download.s3.amazonaws.com/REPO/install.py)"

worked, i think it's a problem with an evolution of pgsql-io .

Maybe i can try to install instant client with another way, without pgsql-io.

Thank you

**Comment by Geronium** [comment]
ok, i thinked this new version could support the web use, because when i tried the latest version of pgmanage, the web using was buggy, it didn't support the changing of the root web page. 

So i will wait for a new official version, that support a web use.

thank you for taking up the torch of omnidb.

**Comment by eug3nix** [comment]
Hi.
Just want to let you know that we have releaased
Hi, I have just uploaded binaries for Release Candidate 2 which includes the latest Pgmanage features and bugfixes.
You can find the binaries in the releases section of the project: https://github.com/commandprompt/pgmanage/releases/tag/1.0.0rc2

We will be releasing an official 1.0 version on the next week.

Thanks

**Comment by Geronium** [comment]
Hello, i just tried to build the docker image of the new version of pgmanage, and i got an "error 500" 

"[05/13/2024 15:44:45] WARNING [django.request:224] Not Found: /favicon.ico
^C^C^C^C^C
^C^C^C
[05/13/2024 16:04:35] ERROR [django.request:224] Internal Server Error: /pgmanage_login/
Traceback (most recent call last):
  File "/home/omnidb/.venv/omnidb/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/omnidb/.venv/omnidb/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/omnidb/OmniDB/pgmanage/app/views/login.py", line 82, in index
    return HttpResponse(template.render(context, request))
  File "/home/omnidb/.venv/omnidb/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/omnidb/.venv/omnidb/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/omnidb/.venv/omnidb/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/omnidb/.venv/omnidb/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/omnidb/.venv/omnidb/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/omnidb/.venv/omnidb/lib/python3.9/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/omnidb/.venv/omnidb/lib/python3.9/site-packages/django/utils/safestring.py", line 46, in wrapped
    return safety_marker(func(*args, **kwargs))
  File "/home/omnidb/.venv/omnidb/lib/python3.9/site-packages/django_vite/templatetags/django_vite.py", line 660, in vite_asset
    return DjangoViteAssetLoader.instance().generate_vite_asset(path, **kwargs)
  File "/home/omnidb/.venv/omnidb/lib/python3.9/site-packages/django_vite/templatetags/django_vite.py", line 128, in generate_vite_asset
    raise RuntimeError(
RuntimeError: Cannot find src/login.js in Vite manifest at /home/omnidb/OmniDB/pgmanage/app/static/assets/js/dist/manifest.json
[05/13/2024 16:04:35] WARNING [django.request:224] Not Found: /favicon.ico"

I think, that could be because i didn't run  

"npm run dev"

but this is because i can't have at the same time  in the entry point of my docker image "npm run dev" and "python3.9 pgmanage-server.py".

**Comment by Geronium** [comment]
Hello, 

i find a solution to run the "npm run dev" but i have already the same error 500, the new docker file :

FROM ubuntu:focal


LABEL maintainer="OmniDB-NG team"

ARG OMNIDB_VERSION=3.0.6

SHELL ["/bin/bash", "-c"]

USER root


RUN apt-get update
RUN apt install -y python3-launchpadlib
RUN apt install -y software-properties-common && add-apt-repository ppa:deadsnakes/ppa
RUN addgroup --system omnidb && adduser --system omnidb --ingroup omnidb
RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC  apt install -y python3.9 curl wget vim sudo software-properties-common libpq-dev libsasl2-dev python3.9-dev python3-pip libldap2-dev libssl-dev  python3.9-venv python3-launchpadlib python3-wheel


#RUN apt install -y libsasl2-dev python3-dev python3-pip libldap2-dev libssl-dev  python3-venv

RUN  apt-get -y --fix-missing install cl-sql-oracle postgresql-client cl-postgres libpq5 alien debhelper

RUN wget https://download.oracle.com/otn_software/linux/instantclient/19600/oracle-instantclient19.6-basiclite-19.6.0.0.0-1.x86_64.rpm && wget https://download.oracle.com/otn_software/linux/instantclient/19600/oracle-instantclient19.6-sqlplus-19.6.0.0.0-1.x86_64.rpm && wget https://download.oracle.com/otn_software/linux/instantclient/19600/oracle-instantclient19.6-devel-19.6.0.0.0-1.x86_64.rpm 
RUN alien -i oracle-instantclient19.6-basiclite-19.6.0.0.0-1.x86_64.rpm 
RUN alien -i oracle-instantclient19.6-devel-19.6.0.0.0-1.x86_64.rpm 
RUN echo /usr/lib/oracle/19.6/client64/lib > /etc/ld.so.conf.d/oracle.conf && rm -f oracle-instantclient*

RUN ls /opt 

ENV ORACLE_HOME=/opt/instantclient_19_6
ENV LD_LIBRARY_PATH=${ORACLE_HOME}
ENV PATH=/usr/local/bin:/home/omnidb/.local/bin:$ORACLE_HOME:$PATH


RUN apt-get install -y python3-setuptools


USER omnidb:omnidb
ENV HOME /home/omnidb

WORKDIR ${HOME}
RUN wget https://github.com/commandprompt/pgmanage/archive/refs/tags/1.0.tar.gz \
    && tar -xf 1.0.tar.gz \
    && mv pgmanage-1.0 OmniDB \
    && ls OmniDB

RUN python3.9 -m venv .venv/omnidb 
RUN .venv/omnidb/bin/pip3.9 install  -r /home/omnidb/OmniDB/requirements.txt
RUN .venv/omnidb/bin/pip3.9 install  python-ldap django-auth-ldap

USER root
RUN apt-get -y install npm
RUN npm install -g npm 

RUN curl -sL https://deb.nodesource.com/setup_22.x | bash - 
RUN apt-get install -y nodejs


RUN node --version
RUN npm --version


RUN rm -f /home/omnidb/OmniDB/pgmanage/app/static/assets/js/pgmanage_frontend/package-lock.json

RUN cd /home/omnidb/OmniDB/pgmanage/app/static/assets/js/pgmanage_frontend/ && npm install && npm i vite@latest -D

USER omnidb:omnidb
WORKDIR ${HOME}/OmniDB/pgmanage
RUN source /home/omnidb/.venv/omnidb/bin/activate && sed -i "s/LISTENING_ADDRESS    = '127.0.0.1'/LISTENING_ADDRESS = '0.0.0.0'/g" config.py 


EXPOSE 8000

RUN cd ${HOME}/OmniDB/pgmanage && echo -e "cd /home/omnidb/OmniDB/pgmanage/app/static/assets/js/pgmanage_frontend/ \nnohup npm run dev& \nsource /home/omnidb/.venv/omnidb/bin/activate\ncd ${HOME}/OmniDB/pgmanage \npython3.9 pgmanage-server.py" >> scriptLancement.sh && chmod +x scriptLancement.sh

CMD cd ${HOME}/OmniDB/pgmanage  && ./scriptLancement.sh

**Comment by Geronium** [comment]
again the same error 

"RuntimeError: Cannot find src/login.js in Vite manifest at /home/omnidb/OmniDB/pgmanage/app/static/assets/js/dist/manifest.json
[05/14/2024 13:44:24] WARNING [django.request:224] Not Found: /favicon.ico
[05/14/2024 13:44:30] ERROR [django.request:224] Internal Server Error: /pgmanage_login/
Traceback (most recent call last):
  File "/home/omnidb/.venv/omnidb/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/omnidb/.venv/omnidb/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/omnidb/OmniDB/pgmanage/app/views/login.py", line 82, in index
    return HttpResponse(template.render(context, request))
  File "/home/omnidb/.venv/omnidb/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/omnidb/.venv/omnidb/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/omnidb/.venv/omnidb/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/omnidb/.venv/omnidb/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/omnidb/.venv/omnidb/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/omnidb/.venv/omnidb/lib/python3.9/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/omnidb/.venv/omnidb/lib/python3.9/site-packages/django/utils/safestring.py", line 46, in wrapped
    return safety_marker(func(*args, **kwargs))
  File "/home/omnidb/.venv/omnidb/lib/python3.9/site-packages/django_vite/templatetags/django_vite.py", line 660, in vite_asset
    return DjangoViteAssetLoader.instance().generate_vite_asset(path, **kwargs)
  File "/home/omnidb/.venv/omnidb/lib/python3.9/site-packages/django_vite/templatetags/django_vite.py", line 128, in generate_vite_asset
    raise RuntimeError(
RuntimeError: Cannot find src/login.js in Vite manifest at /home/omnidb/OmniDB/pgmanage/app/static/assets/js/dist/manifest.json
[05/14/2024 13:44:30] WARNING [django.request:224] Not Found: /favicon.ico"
