### ISSUE TITLE
mask sensitive information in pgmanage.log

### ISSUE THREAD

**Issue by eug3nix** [commandprompt/pgmanage#398]
Here is an excerpt from pgmanage log that illustrates why this should be done:
`
[04/10/2024 13:16:31] ERROR [pid:1175428] [app.views.logging:14] [request_id:1] "POST /master_password/"
AxiosError: Request failed with status code 400
    at jw (http://localhost:25869/static/assets/js/dist/assets/omnidb.js:56:1050)
    at XMLHttpRequest.P (http://localhost:25869/static/assets/js/dist/assets/omnidb.js:56:4249)
request_data: {"master_password":"Supersecurepasswordgoeshere!"}
response_data: "Master password is not correct."
`

**Comment by eug3nix** [comment]
completed.
